// <auto-generated />
using System;
using BookOnline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookOnline.Migrations
{
    [DbContext(typeof(BookOnlineDatabaseContext))]
    [Migration("20220629203909_InitailCreate")]
    partial class InitailCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookOnline.Models.Account", b =>
                {
                    b.Property<int>("Account_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account_ConfirmPassword")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Account_Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Account_Name")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Account_Password")
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("Account_Phone")
                        .HasColumnType("int");

                    b.Property<bool>("Account_Status")
                        .HasColumnType("bit");

                    b.Property<int>("Account_Type")
                        .HasColumnType("int");

                    b.HasKey("Account_Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BookOnline.Models.Book", b =>
                {
                    b.Property<int>("Book_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Book_Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Book_Category")
                        .HasColumnType("int");

                    b.Property<string>("Book_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Book_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Book_Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Book_NXB")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Book_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Book_ShortContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<bool>("Book_Status")
                        .HasColumnType("bit");

                    b.Property<int>("Book_View")
                        .HasColumnType("int");

                    b.Property<int?>("Category_Id")
                        .HasColumnType("int");

                    b.HasKey("Book_Id");

                    b.HasIndex("Category_Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookOnline.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category_DataName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Category_Status")
                        .HasColumnType("bit");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookOnline.Models.Book", b =>
                {
                    b.HasOne("BookOnline.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("Category_Id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookOnline.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
